package com.elderlyos.vieuxos

import android.content.Context

data class AppStrings(
    // Home tiles
    val callFamily: String,
    val takeHome: String,
    val camera: String,
    val gallery: String,
    val messages: String,
    val sos: String,
    val internet: String,
    val weather: String,
    val youtube: String,
    val wallet: String,
    val torch: String,
    // Setup
    val setupTitle: String,
    val general: String,
    val contacts: String,
    val medications: String,
    val events: String,
    val saveAll: String,
    val savedOk: String,
    val personName: String,
    val homeAddress: String,
    val changePin: String,
    val meetLink: String,
    val addContact: String,
    val addMedication: String,
    val addEvent: String,
    // PIN screen
    val familySetup: String,
    val enterPin: String,
    val unlock: String,
    val wrongPin: String,
    // Language
    val language: String,
    // SOS
    val callForHelp: String,
    val howItWorks: String,
    val howItWorksBody: String,
    // Phone
    val phone: String,
    // Meals
    val breakfast: String,
    val lunch: String,
    val dinner: String,
    // Gallery
    val galleryTitle: String,
    val noMedia: String,
    val backToGallery: String,
    // Misc
    val cancel: String,
    val add: String,
    val save: String,
)

private val EN = AppStrings(
    callFamily    = "Call Family",
    takeHome      = "Take Me Home",
    camera        = "Camera",
    gallery       = "Gallery",
    messages      = "Messages",
    sos           = "SOS",
    internet      = "Internet",
    weather       = "Weather",
    youtube       = "YouTube",
    wallet        = "Wallet",
    torch         = "Torch",
    setupTitle    = "Setup",
    general       = "General",
    contacts      = "Contacts",
    medications   = "Medications",
    events        = "Calendar Events",
    saveAll       = "Save All",
    savedOk       = "Settings saved!",
    personName    = "Person's Name",
    homeAddress   = "Home Address",
    changePin     = "Change PIN",
    meetLink      = "Google Meet Link",
    addContact    = "Add contact",
    addMedication = "Add medication",
    addEvent      = "Add event",
    familySetup   = "Family Setup",
    enterPin      = "Enter PIN to continue",
    unlock        = "Unlock",
    wrongPin      = "Wrong PIN",
    language      = "Language",
    callForHelp   = "CALL FOR HELP",
    howItWorks    = "ℹ️  How it works",
    howItWorksBody = "1. Tap CALL FOR HELP\n2. Choose who to contact\n3. They receive an SMS with the Meet link\n4. The Meet room opens on your phone",
    phone         = "Phone",
    breakfast     = "Breakfast",
    lunch         = "Lunch",
    dinner        = "Dinner",
    galleryTitle  = "Gallery",
    noMedia       = "No photos or videos found",
    backToGallery = "Back to Gallery",
    cancel        = "Cancel",
    add           = "Add",
    save          = "Save",
)

private val FR = AppStrings(
    callFamily    = "Appeler Famille",
    takeHome      = "Rentrer",
    camera        = "Photo",
    gallery       = "Galerie",
    messages      = "Messages",
    sos           = "SOS",
    internet      = "Internet",
    weather       = "Météo",
    youtube       = "YouTube",
    wallet        = "Portefeuille",
    torch         = "Lampe",
    setupTitle    = "Configuration",
    general       = "Général",
    contacts      = "Contacts",
    medications   = "Médicaments",
    events        = "Agenda",
    saveAll       = "Tout Enregistrer",
    savedOk       = "Paramètres sauvegardés !",
    personName    = "Nom de la personne",
    homeAddress   = "Adresse du domicile",
    changePin     = "Changer le code PIN",
    meetLink      = "Lien Google Meet",
    addContact    = "Ajouter un contact",
    addMedication = "Ajouter un médicament",
    addEvent      = "Ajouter un événement",
    familySetup   = "Configuration",
    enterPin      = "Entrez le code PIN",
    unlock        = "Déverrouiller",
    wrongPin      = "Code PIN incorrect",
    language      = "Langue",
    callForHelp   = "APPELER À L'AIDE",
    howItWorks    = "ℹ️  Comment ça marche",
    howItWorksBody = "1. Appuyez sur APPELER À L'AIDE\n2. Choisissez qui contacter\n3. Ils reçoivent un SMS avec le lien Meet\n4. La réunion Meet s'ouvre sur votre téléphone",
    phone         = "Téléphone",
    breakfast     = "Petit-déjeuner",
    lunch         = "Déjeuner",
    dinner        = "Dîner",
    galleryTitle  = "Galerie",
    noMedia       = "Aucune photo ou vidéo trouvée",
    backToGallery = "Retour à la galerie",
    cancel        = "Annuler",
    add           = "Ajouter",
    save          = "Enregistrer",
)

private val NL = AppStrings(
    callFamily    = "Familie Bellen",
    takeHome      = "Naar Huis",
    camera        = "Camera",
    gallery       = "Galerij",
    messages      = "Berichten",
    sos           = "SOS",
    internet      = "Internet",
    weather       = "Weer",
    youtube       = "YouTube",
    wallet        = "Portemonnee",
    torch         = "Zaklamp",
    setupTitle    = "Instellingen",
    general       = "Algemeen",
    contacts      = "Contacten",
    medications   = "Medicijnen",
    events        = "Agenda",
    saveAll       = "Alles Opslaan",
    savedOk       = "Instellingen opgeslagen!",
    personName    = "Naam van de persoon",
    homeAddress   = "Thuisadres",
    changePin     = "PIN wijzigen",
    meetLink      = "Google Meet link",
    addContact    = "Contact toevoegen",
    addMedication = "Medicijn toevoegen",
    addEvent      = "Afspraak toevoegen",
    familySetup   = "Instellingen",
    enterPin      = "Voer PIN-code in",
    unlock        = "Ontgrendelen",
    wrongPin      = "Verkeerde PIN",
    language      = "Taal",
    callForHelp   = "HULP ROEPEN",
    howItWorks    = "ℹ️  Hoe het werkt",
    howItWorksBody = "1. Tik op HULP ROEPEN\n2. Kies wie u wilt bellen\n3. Ze ontvangen een sms met de Meet-link\n4. De Meet-vergadering opent op uw telefoon",
    phone         = "Telefoon",
    breakfast     = "Ontbijt",
    lunch         = "Lunch",
    dinner        = "Avondeten",
    galleryTitle  = "Galerij",
    noMedia       = "Geen foto's of video's gevonden",
    backToGallery = "Terug naar galerij",
    cancel        = "Annuleren",
    add           = "Toevoegen",
    save          = "Opslaan",
)

fun getStrings(context: Context): AppStrings {
    val lang = context.getSharedPreferences("vieuxos_prefs", Context.MODE_PRIVATE)
        .getString("language", "en") ?: "en"
    return when (lang) {
        "fr" -> FR
        "nl" -> NL
        else -> EN
    }
}
